export const FETCH_PRODUCT_LIST='FETCH_PRODUCT_LIST';
export const ADD_CARD_PRODUCT ='ADD_CARD_PRODUCT';
export const REMOVE_CARD_PRODUCT ='REMOVE_CARD_PRODUCT';
export const GET_CARD_PRODUCT = 'GET_CARD_PRODUCT';
export const GET_ACTIVE_PAGE = 'GET_ACTIVE_PAGE'