export const FETCH_PRODUCT_LIST='FETCH_PRODUCT_LIST';
export const ADD_CARD_PRODUCT ='ADD_CARD_PRODUCT';
export const REMOVE_CARD_PRODUCT ='REMOVE_CARD_PRODUCT';
export const GET_CARD_PRODUCT = 'GET_CARD_PRODUCT';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const INIT_ACTIVE_PAGE = 'INIT_ACTIVE_PAGE';
export const GET_NUMBERS_OF_PAGE = 'GET_NUMBERS_OF_PAGE';


